<?php

namespace Taseera\BackendBundle\Repository;

/**
 * TCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCityRepository extends \Doctrine\ORM\EntityRepository
{
}
