<?php

namespace Taseera\BackendBundle\Repository;

/**
 * TCityAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCityAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
