<?php

namespace Taseera\BackendBundle\Repository;

/**
 * TCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
