<?php

namespace Taseera\BackendBundle\Repository;

/**
 * TRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
