<?php

namespace Taseera\BackendBundle\Repository;

/**
 * TUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TUserRepository extends \Doctrine\ORM\EntityRepository
{
}
