tuser_company_index:
    path:     /
    defaults: { _controller: "TaseeraBackendBundle:TUserCompany:index" }
    methods:  GET

tuser_company_show:
    path:     /{id}/show
    defaults: { _controller: "TaseeraBackendBundle:TUserCompany:show" }
    methods:  GET

tuser_company_new:
    path:     /new
    defaults: { _controller: "TaseeraBackendBundle:TUserCompany:new" }
    methods:  [GET, POST]

tuser_company_edit:
    path:     /{id}/edit
    defaults: { _controller: "TaseeraBackendBundle:TUserCompany:edit" }
    methods:  [GET, POST]

tuser_company_delete:
    path:     /{id}/delete
    defaults: { _controller: "TaseeraBackendBundle:TUserCompany:delete" }
    methods:  DELETE
